Fix laravel template and disable VPC endpoint S3 in common stack

diff --git a/templates/laravel-instances.cfn.yml b/templates/laravel-instances.cfn.yml
--- a/templates/laravel-instances.cfn.yml
+++ b/templates/laravel-instances.cfn.yml
@@ -366,7 +366,7 @@ Resources:
     Metadata:
       'AWS::CloudFormation::Init':
         configSets:
-          default: [awslogs, config]
+          default: [awslogs, config, php, nodejs, nginx, laravel]
         awslogs:
           packages:
             yum:
@@ -484,6 +484,7 @@ Resources:
                 files:
                   - '/etc/awslogs/awslogs.conf'
                   - '/etc/awslogs/awscli.conf'
+                  - '/etc/awslogs/config/*'
         config:
           packages:
             yum:
@@ -506,12 +507,17 @@ Resources:
                 action=/opt/aws/bin/cfn-init --verbose --stack=${AWS::StackName} --region=${AWS::Region} --resource=LaunchConfiguration
                 runas=root
           commands:
-            10_enable_nginx_repo:
+            10_update_packages:
+              command: 'yum update -y'
+            11_enable_nginx_repo:
               command: 'amazon-linux-extras enable nginx1.12'
-              test: '[ ! grep -Fxq "[amzn2extra-nginx1.12]" /etc/yum.repos.d/amzn2-extras.repo ]'
-            10_enable_php_repo:
+              test: '! grep -Fxq "[amzn2extra-nginx1.12]" /etc/yum.repos.d/amzn2-extras.repo'
+            12_enable_php_repo:
               command: 'amazon-linux-extras enable php7.2'
-              test: '[ ! grep -Fxq "[amzn2extra-php7.2]" /etc/yum.repos.d/amzn2-extras.repo ]'
+              test: '! grep -Fxq "[amzn2extra-php7.2]" /etc/yum.repos.d/amzn2-extras.repo'
+            13_add_node_repo:
+              command: 'curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -'
+              test: '[ ! -f /etc/yum.repos.d/nodesource-el7.repo ]'
           services:
             sysvinit:
               cfn-hup:
@@ -520,6 +526,149 @@ Resources:
                 files:
                   - '/etc/cfn/cfn-hup.conf'
                   - '/etc/cfn/hooks.d/cfn-auto-reloader.conf'
+        php:
+          packages:
+            yum:
+              php-bcmath: []
+              php-cli: []
+              php-fpm: []
+              php-gd: []
+              php-intl: []
+              php-json: []
+              php-mbstring: []
+              php-mysqlnd: []
+              php-opcache: []
+              php-pdo: []
+              # php-pecl-memcache: []
+              php-pecl-zip: []
+              php-xml: []
+          files:
+            '/etc/awslogs/config/php.conf':
+              content: !Sub |
+                [/var/log/php-fpm/www-error.log]
+                datetime_format = %b %d %H:%M:%S
+                file = /var/log/php-fpm/www-error.log
+                log_stream_name = {instance_id}/var/log/php-fpm/www-error.log
+                log_group_name = ${Logs}
+                [/var/log/php-fpm/www-slow.log]
+                datetime_format = %b %d %H:%M:%S
+                file = /var/log/php-fpm/www-slow.log
+                log_stream_name = {instance_id}/var/log/php-fpm/www-slow.log
+                log_group_name = ${Logs}
+              mode: '000600'
+              owner: root
+              group: root
+            '/tmp/config-php-ini.sh':
+              content: |
+                #!/bin/bash -ex
+                sed -i 's|;*expose_php=.*|expose_php=0|g' /etc/php.ini
+                sed -i 's|;*memory_limit = 128M|memory_limit = 512M|g' /etc/php.ini
+                sed -i 's|;*post_max_size = 8M|post_max_size = 50M|g' /etc/php.ini
+                sed -i 's|;*upload_max_filesize = 2M|upload_max_filesize = 20M|g' /etc/php.ini
+                sed -i 's|;*max_file_uploads = 20|max_file_uploads = 20|g' /etc/php.ini
+                sed -i 's|;*opcache.memory_consumption=128|opcache.memory_consumption=256|g' /etc/php.d/10-opcache.ini
+                sed -i 's|;*opcache.interned_strings_buffer=8|opcache.interned_strings_buffer=16|g' /etc/php.d/10-opcache.ini
+                sed -i 's|;*opcache.max_accelerated_files=4000|opcache.max_accelerated_files=10000|g' /etc/php.d/10-opcache.ini
+                sed -i 's|;*opcache.max_wasted_percentage=5|opcache.max_wasted_percentage=10|g' /etc/php.d/10-opcache.ini
+                sed -i 's|;*opcache.validate_timestamps=1|opcache.validate_timestamps=1|g' /etc/php.d/10-opcache.ini
+                sed -i 's|;*opcache.revalidate_freq=2|opcache.revalidate_freq=60|g' /etc/php.d/10-opcache.ini
+                sed -i 's|;*opcache.fast_shutdown=0|opcache.fast_shutdown=0|g' /etc/php.d/10-opcache.ini
+              mode: '000500'
+              owner: root
+              group: root
+            '/tmp/install-pecl-packages.sh':
+              content: |
+                #!/bin/bash -ex
+                yum install -y gcc php-devel php-pear ImageMagick-devel ImageMagick
+
+                pecl install imagick
+                echo 'extension=imagick.so' > /etc/php.d/20-imagick.ini
+
+                pecl install redis
+                echo 'extension=redis.so' > /etc/php.d/20-redis.ini
+
+                yum remove -y gcc php-devel php-pear ImageMagick-devel
+
+                service php-fpm restart
+              mode: '000500'
+              owner: root
+              group: root
+            '/tmp/get-composer.sh':
+              content: |
+                #!/bin/bash -ex
+
+                if [ -f /usr/local/bin/composer ]
+                then
+                    /usr/local/bin/composer self-update
+                    exit $?
+                fi
+
+                yum install -y git wget
+
+                EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
+                php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+                ACTUAL_SIGNATURE="$(php -r "echo hash_file('SHA384', 'composer-setup.php');")"
+
+                if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+                then
+                    >&2 echo 'ERROR: Invalid installer signature'
+                    rm composer-setup.php
+                    exit 1
+                fi
+
+                php composer-setup.php --quiet --install-dir=/usr/local/bin/ --filename=composer
+                RESULT=$?
+                rm composer-setup.php
+                exit $RESULT
+              mode: '000500'
+              owner: root
+              group: root
+            '/var/app/current/index.php':
+              content: |
+                <?php phpinfo();
+              mode: '000644'
+              owner: ec2-user
+              group: apache
+          commands:
+            20_user_group:
+              command: 'usermod -a -G apache ec2-user'
+            21_config_php_ini:
+              command: '/tmp/config-php-ini.sh'
+            22_install_pecl_packages:
+              command: '/tmp/install-pecl-packages.sh'
+            23_get_composer:
+              command: '/tmp/get-composer.sh'
+              test: '[ ! -f /usr/local/bin/composer ]'
+              env:
+                HOME: /root
+                COMPOSER_HOME: /root
+            24_chown_web_dir:
+              command: 'chown -R ec2-user:apache /var/app'
+          services:
+            sysvinit:
+              php-fpm:
+                enabled: true
+                ensureRunning: true
+                packages:
+                  yum:
+                    - php-*
+                files:
+                  - '/etc/php.ini'
+                  - '/etc/php.d/*'
+                  - '/etc/php-fpm.conf'
+                  - '/etc/php-fpm.d/*'
+        nodejs:
+          packages:
+            yum:
+              gcc: []
+              gcc-c++: []
+              make: []
+              nodejs: []
+          commands:
+            30_update_npm:
+              command: npm install -y -g npm
+            31_install_laravel_echo_server:
+              command: npm install -y -g laravel-echo-server
         nginx:
           packages:
             yum:
@@ -540,9 +689,88 @@ Resources:
               mode: '000600'
               owner: root
               group: root
+            '/etc/nginx/nginx.conf':
+              content: |
+                user apache;
+                worker_processes auto;
+                error_log /var/log/nginx/error.log;
+                pid /run/nginx.pid;
+
+                # Load dynamic modules. See /usr/share/nginx/README.dynamic.
+                include /usr/share/nginx/modules/*.conf;
+
+                events {
+                    worker_connections 1024;
+                }
+
+                http {
+                    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
+                                      '$status $body_bytes_sent "$http_referer" '
+                                      '"$http_user_agent" "$http_x_forwarded_for"';
+
+                    access_log  /var/log/nginx/access.log  main;
+
+                    sendfile            on;
+                    tcp_nopush          on;
+                    tcp_nodelay         on;
+                    keepalive_timeout   65;
+                    types_hash_max_size 2048;
+                    server_tokens       off;
+
+                    include             /etc/nginx/mime.types;
+                    default_type        application/octet-stream;
+
+                    # Load modular configuration files from the /etc/nginx/conf.d directory.
+                    # See http://nginx.org/en/docs/ngx_core_module.html#include
+                    # for more information.
+                    include /etc/nginx/conf.d/*.conf;
+
+                    server {
+                        listen       80 default_server;
+                        listen       [::]:80 default_server;
+                        server_name  _;
+                        root         /var/app/current;
+
+                        # Load configuration files for the default server block.
+                        include /etc/nginx/default.d/*.conf;
+
+                        # This will pass all unknown URIs to index.php. Most frameworks
+                        # work this way. Remove, if you don't need this.
+                        location / {
+                            set $redirect 0;
+                            if ($http_x_forwarded_proto != "https") {
+                                set $redirect 1;
+                            }
+                            if ($http_user_agent ~* "ELB-HealthChecker") {
+                                set $redirect 0;
+                            }
+                            if ($redirect = 1) {
+                                return 301 https://$host$request_uri;
+                            }
+
+                            try_files $uri $uri/ index.php?$args;
+                        }
+
+                        error_page 404 /404.html;
+                        location = /40x.html {
+                        }
+
+                        error_page 500 502 503 504 /50x.html;
+                        location = /50x.html {
+                        }
+
+                        location ~ /\.ht {
+                            access_log off;
+                            deny  all;
+                        }
+                    }
+                }
+              mode: '000644'
+              owner: root
+              group: root
           commands:
-            40_user_group:
-              command: 'usermod -a -G apache ec2-user'
+            40_chown_log_dir:
+              command: 'chown -R apache:apache /var/log/nginx'
           services:
             sysvinit:
               nginx:
@@ -555,106 +783,21 @@ Resources:
                   - '/etc/nginx/nginx.conf'
                   - '/etc/nginx/conf.d/*'
                   - '/etc/nginx/default.d/*'
-        php:
-          packages:
-            yum:
-              php-bcmath: []
-              php-cli: []
-              php-fpm: []
-              php-gd: []
-              php-intl: []
-              php-json: []
-              php-mbstring: []
-              php-mysqlnd: []
-              php-opcache: []
-              php-pdo: []
-              # php-pecl-igbinary: []
-              # php-pecl-redis: []
-              # php-pecl-imagick: []
-              php-xml: []
-              php-zip: []
-          files:
-            '/etc/awslogs/config/php.conf':
-              content: !Sub |
-                [/var/log/php-fpm/www-error.log]
-                datetime_format = %b %d %H:%M:%S
-                file = /var/log/php-fpm/www-error.log
-                log_stream_name = {instance_id}/var/log/php-fpm/www-error.log
-                log_group_name = ${Logs}
-                [/var/log/php-fpm/www-slow.log]
-                datetime_format = %b %d %H:%M:%S
-                file = /var/log/php-fpm/www-slow.log
-                log_stream_name = {instance_id}/var/log/php-fpm/www-slow.log
-                log_group_name = ${Logs}
-              mode: '000600'
-              owner: root
-              group: root
-          commands:
-            50_php_upload_max_filesize:
-              command: 'sed -i "s|;*upload_max_filesize =.*|upload_max_filesize=10M|i" /etc/php.ini'
-            51_php_max_file_uploads:
-              command: 'sed -i "s|;*max_file_uploads =.*|max_file_uploads=20|i" /etc/php.ini'
-            52_php_post_max_size:
-              command: 'sed -i "s|;*post_max_size =.*|post_max_size=20M|i" /etc/php.ini'
-            53_php_expose_php:
-              command: 'sed -i "s|;*expose_php=.*|expose_php=0|i" /etc/php.ini'
-          services:
-            sysvinit:
-              php-fpm:
-                enabled: true
-                ensureRunning: true
-                packages:
-                  yum:
-                    - php-*
-                files:
-                  - '/etc/php.ini'
-                  - '/etc/php.d/*'
-                  - '/etc/php-fpm.conf'
-                  - '/etc/php-fpm.d/*'
-        php-extra:
-          packages:
-            yum:
-              gcc: []
-              php-devel: []
-              php-pear: []
-              ImageMagick-devel: []
-          files:
-            '/etc/php.d/20-imagick.ini':
-              content: |
-                extension=imagick.so
-              mode: '000600'
-              owner: root
-              group: root
-            '/etc/php.d/20-redis.ini':
-              content: |
-                extension=redis.so
-              mode: '000600'
-              owner: root
-              group: root
-          commands:
-            60_ext_imagick:
-              command: pecl install imagick
-            61_ext_redis:
-              command: pecl install redis
-            69_restart_fpm:
-              command: service php-fpm restart
-        nodejs:
-          packages:
-            yum:
-              gcc-c++: []
-              make: []
-          commands:
-            70_add_repo:
-              command: curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
-            71_install_nodejs:
-              command: yum install -y nodejs
-            72_update_npm:
-              command: npm install -y -g npm
-            73_install_laravel_echo_server:
-              command: npm install -y -g laravel-echo-server
 
+        laravel:
+          files:
+            '/etc/awslogs/config/laravel.conf':
+              content: !Sub |
+                [/var/app/current/storage/logs/laravel.log]
+                datetime_format = %b %d %H:%M:%S
+                file = /var/app/current/storage/logs/laravel.log
+                log_stream_name = {instance_id}/var/app/current/storage/logs/laravel.log
+                log_group_name = ${Logs}
+              mode: '000600'
+              owner: root
+              group: root
     Properties:
-      AssociatePublicIpAddress: true
+      # AssociatePublicIpAddress: false
       EbsOptimized: false
       IamInstanceProfile: !Ref InstanceProfile
       ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
@@ -677,10 +820,6 @@ Resources:
       LaunchConfigurationName: !Ref LaunchConfiguration
       MaxSize: '4'
       MinSize: '2'
-      Tags:
-        - Key: Name
-          Value: !Sub ${EnvironmentName}-WebAutoScalingGroup
-          PropagateAtLaunch: true
       NotificationConfigurations: !If
         - HasAlertTopic
         - - NotificationTypes:
@@ -688,14 +827,20 @@ Resources:
               - 'autoscaling:EC2_INSTANCE_TERMINATE_ERROR'
             TopicARN: !Ref AlertTopicARN
         - []
+      Tags:
+        - Key: Name
+          Value: !Sub ${EnvironmentName}-WebAutoScalingGroup
+          PropagateAtLaunch: true
+      TargetGroupARNs:
+        - !Ref DefaultTargetGroup
       VPCZoneIdentifier: !Ref PrivateSubnets
     CreationPolicy:
       ResourceSignal:
         Count: 1
-        Timeout: PT10M
+        Timeout: PT15M
     UpdatePolicy:
       AutoScalingRollingUpdate:
-        PauseTime: PT10M
+        PauseTime: PT15M
         SuspendProcesses:
           - HealthCheck
           - ReplaceUnhealthy
